// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2fkKVTy8MnAD1wdQq6GN8795IxK7pkLs',
    appId: '1:736901547046:web:f5ce7e356a4c2aa4a252e7',
    messagingSenderId: '736901547046',
    projectId: 'task-manager-6646b',
    authDomain: 'task-manager-6646b.firebaseapp.com',
    storageBucket: 'task-manager-6646b.firebasestorage.app',
    measurementId: 'G-QF7HY6696T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTnAPjhvolcx9FWjoJSDALzH18azU0Nv8',
    appId: '1:736901547046:android:5c975234a2a95584a252e7',
    messagingSenderId: '736901547046',
    projectId: 'task-manager-6646b',
    storageBucket: 'task-manager-6646b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLd193tdzCrbt4-lczD71MqegT9tBzES0',
    appId: '1:736901547046:ios:10d3bc07ce7a5648a252e7',
    messagingSenderId: '736901547046',
    projectId: 'task-manager-6646b',
    storageBucket: 'task-manager-6646b.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLd193tdzCrbt4-lczD71MqegT9tBzES0',
    appId: '1:736901547046:ios:10d3bc07ce7a5648a252e7',
    messagingSenderId: '736901547046',
    projectId: 'task-manager-6646b',
    storageBucket: 'task-manager-6646b.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2fkKVTy8MnAD1wdQq6GN8795IxK7pkLs',
    appId: '1:736901547046:web:3c136c8581af18d8a252e7',
    messagingSenderId: '736901547046',
    projectId: 'task-manager-6646b',
    authDomain: 'task-manager-6646b.firebaseapp.com',
    storageBucket: 'task-manager-6646b.firebasestorage.app',
    measurementId: 'G-Q917TMFMZ6',
  );

}